function show_help() {
    echo "Uso: $0 <comando> [repositorio]"
    echo ""
    echo "Comandos:"
    echo "  start    Inicia el contenedor del repositorio indicado."
    echo "  stop     Detiene el contenedor del repositorio indicado."
    echo "  build    Crea y arranca el contenedor del repositorio indicado."
    echo "  status   Muestra el estado de todos los contenedores."
    echo "  logs     Muestra los logs del contenedor indicado."
    echo "  exec     Abre una terminal en el contenedor indicado."
    echo "  list     Lista los repositorios disponibles."
    echo ""
    echo "Opciones:"
    echo "  repositorio     El nombre del repositorio a ejecutar."
    echo ""
    echo "Ejemplos:"
    echo "  $0 start mi_repositorio"
    echo "  $0 logs mi_repositorio"
    echo "  $0 exec mi_repositorio"
    echo "  $0 list"
}